apiVersion: v1
kind: Namespace
metadata:
  name: sundaynightns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sundaynightsa
  namespace: sundaynightns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sundaynight-role
rules:
- apiGroups: ["", "pods", "networking.k8s.io", "apiextensions.k8s.io", "storage.k8s.io", "operator.openshift.io"]
  resources: ["namespaces", "customresourcedefinitions", "storageclasses", "ingresses"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sundaynight-rolebinding
subjects:
- kind: ServiceAccount
  name: sundaynightsa
  namespace: sundaynightns
roleRef:
  kind: ClusterRole
  name: sundaynight-role
  apiGroup: rbac.authorization.k8s.io
---
